// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDB-nvlGoipQsaZjlrmFiX8lo2LAr8UmJQ',
    appId: '1:225020428722:web:c67c8c947bc3a5708e64ab',
    messagingSenderId: '225020428722',
    projectId: 'primec-market',
    authDomain: 'primec-market.firebaseapp.com',
    storageBucket: 'primec-market.appspot.com',
    measurementId: 'G-H3H9S1XM07',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJBnXiXARO9k61oUGLouzdU8xmlnMr0rk',
    appId: '1:225020428722:android:f90e6596dc2882498e64ab',
    messagingSenderId: '225020428722',
    projectId: 'primec-market',
    storageBucket: 'primec-market.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCp8lw-yYb05bSin0ulMx9qzAOnRg9S7GA',
    appId: '1:225020428722:ios:3bf7503ba1accd2c8e64ab',
    messagingSenderId: '225020428722',
    projectId: 'primec-market',
    storageBucket: 'primec-market.appspot.com',
    iosClientId: '225020428722-uoujithpl9u09n7jndrlk3ioflidkeor.apps.googleusercontent.com',
    iosBundleId: 'com.example.primecMarket',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCp8lw-yYb05bSin0ulMx9qzAOnRg9S7GA',
    appId: '1:225020428722:ios:318a63b5faacebe38e64ab',
    messagingSenderId: '225020428722',
    projectId: 'primec-market',
    storageBucket: 'primec-market.appspot.com',
    iosClientId: '225020428722-mpf9i327lc1gjtlffn4ctvrgvcmd2bgk.apps.googleusercontent.com',
    iosBundleId: 'com.example.primecMarket.RunnerTests',
  );
}
